name: Ruby-Rspec

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 1.9.3-p551
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
